language: php

php:
  - 7.2
  - 7.3

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - composer check-coding-standard
services:
  - redis-server